/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diagramsj_test_jniclass_ObserverUninstall */

#ifndef _Included_com_diagramsj_test_jniclass_ObserverUninstall
#define _Included_com_diagramsj_test_jniclass_ObserverUninstall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_diagramsj_test_jniclass_ObserverUninstall
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_diagramsj_test_jniclass_ObserverUninstall_init
        (JNIEnv *, jobject, jstring, jstring,jstring);

/*
 * Class:     com_diagramsj_test_jniclass_ObserverUninstall
 * Method:    updateData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_com_diagramsj_test_jniclass_ObserverUninstall_updateData
        (JNIEnv *, jobject, jstring, jstring,jstring);

#ifdef __cplusplus
}
#endif
#endif
